### ISSUE TITLE
package embed: unrecognized import path "embed" (import path does not begin with hostname)

### ISSUE THREAD

**Issue by melvincarvalho** [qbit/widdler#1]
When I run:

```
go get -u suah.dev/widdler
```

I get:

> package embed: unrecognized import path "embed" (import path does not begin with hostname)

**Comment by qbit** [comment]
Hi, what version of Go do you have installed? Widdler needs at lest 1.16 (which is when `embed` was added).

**Comment by melvincarvalho** [comment]
Thanks, I'm using 1.13 on ubuntu 20.04, but I will upgrade

**Comment by qbit** [comment]
If you upgrade to Go 1.17 you will also need to use "install" vs "get": `go install suah.dev/widdler@latest`

**Comment by qbit** [comment]
It seems ya have it running now - I am gonna close this :D
