### ISSUE TITLE
Will a version with individual tiddlers be possible?

### ISSUE THREAD

**Issue by kseistrup** [qbit/widdler#11]
The orginal TiddlyWiki has a variant in which tiddlers are saved as individual files. Would the same be possible to achieve for Widdler?

**Comment by qbit** [comment]
Do you have a link to it? Is it part of the official release or a plugin?

**Comment by kseistrup** [comment]
I'm sorry I didn't give you a link right away. Here it is:

* https://tiddlywiki.com/#TiddlyWiki%20on%20Node.js

It's an official flavour.

I used to run it on ArchLinux:

* https://aur.archlinux.org/packages/nodejs-tiddlywiki

**Comment by kseistrup** [comment]
Thanks, mate.

**Comment by Dialga** [comment]
Use https://gitlab.com/opennota/widdly with flat file store.
