### ISSUE TITLE
[BUG] Index.html does not save

### ISSUE THREAD

**Issue by kookma** [qbit/widdler#14]
1. running widdler using

```
widdler -auth=false -wikis ~/wiki`
```

2. Opining the http://localhost:8080 in browser, opens the `index.html` (this is a Tiddlywiki 5.2.1 file) 
3. Change in index.html does not trigger Widdler to save the index.html nor clicking on save button, save it, instead a save window opens and asks for a file name

If you open `http://localhost:8080/index.html` everything works as expected

**Expected behaviour**

Opening `http://localhost:8080`, browser opens index.html (when it exists), one expects Widdler saves into `index.html`

**Comment by qbit** [comment]
Hi @kookma, would you be able to test #15 and see if it fixes the issue for you?

**Comment by kookma** [comment]
@qbit I need to have a widdler.exe to test!
Sorry, but I have not golang compiler on my machine, nor familiar with golang to build the Widdler.exe!
Is it possible to share a Win 64 binary for test?

**Comment by qbit** [comment]
> @qbit I need to have a widdler.exe to test!

Here ya go! [widdler.zip](https://github.com/qbit/widdler/files/7699318/widdler.zip)

**Comment by kookma** [comment]
@qbit 

I get this 

```
This version of C:\TW\TW-Lab\widdler\widdler.exe is not compatible with the version of Windows you're running. Check your computer's system information and then contact the software publisher.
```

My system is Win 10 64B

**Comment by qbit** [comment]
Dang. Ok. It’s working for me, so I will probably just push the change and cut a new release here shortly.

**Comment by qbit** [comment]
New release has the fix - let me know if it doesn't work!

**Comment by kookma** [comment]
Thank you! The new 1.2.3 worked for me too!

**Comment by amreus** [comment]
So is there a way to list the files in the folder like the previous version?

**Comment by qbit** [comment]
@amreus does it list if you remove the “/“ from the url? So like “http://localhost:8080” vs “http://localhost:8080/“?

**Comment by amreus** [comment]
> @amreus does it list if you remove the “/“ from the url? So like “[http://localhost:8080”](http://localhost:8080%E2%80%9D) vs “[http://localhost:8080/“](http://localhost:8080/%E2%80%9C)?

No, it always creates `index.html` no matter what.

**Comment by amreus** [comment]
Something odd is happening on my end.  When I use a random port instead of 8080 I do see the directory listing.  Maybe Firefox is being "helpful" or something...  I'll look into it.

**Comment by amreus** [comment]
This is how I am starting `widdler`:

```
@echo off
setlocal

set port=8080
REM Random port
if [%1] == [-r] set /a port=(%random%*5000/32768)+2000

call kill widdler

widdler -v

start "" http://localhost:%port%

widdler -auth=false -http :%port% -wikis="%CD%"

```

**Comment by qbit** [comment]
Ah, I noticed chrome does something similar. They seem to cache the redirect or something. Maybe I need to add a header to force invalidation.
