### ISSUE TITLE
How to change the location of the folder where the wiki files gets saved

### ISSUE THREAD

**Issue by arunnbabu81** [qbit/widdler#19]
I would like to change the location of the wiki files created or edited using widdler. Currently wikis are getting saved in the 'users' folder in the C drive of my windows laptop. Is it possible to change the saving folder?

**Comment by qbit** [comment]
widdler takes a `-wikis` flag, by default it uses the directory you are running widdler from.

```
  -wikis string
        Directory of TiddlyWikis to serve over WebDAV. (default "/home/qbit")
```

You can set that to what ever you want and widdler will put the wiki's in that location.

**Comment by arunnbabu81** [comment]
i use `widdler.exe` command in terminal to open the wiki. What exactly should i add to this command to change the folder location as mentioned in the previous post (i don't have much knowledge in these things). I plan to move the wiki to a onedrive folder

**Comment by qbit** [comment]
`widdler.exe -wikis C:\The\Place\you\want\your\wikis` :D - obviously use a real location on your drive :)

**Comment by arunnbabu81** [comment]
Thank you very much for your quick replies and help
