### ISSUE TITLE
Don't create user directories

### ISSUE THREAD

**Issue by CGenie** [qbit/widdler#2]
Hello,
Thank you, this is a nice project!
Is it possible to NOT create user directories inside the `wikis` directory?
Also, how can I turn off `-auth`? I tried `-auth false`, `-auth 0`, `-auth no` but none of that works.

**Comment by CGenie** [comment]
BTW, it would be nice to add comment about command line options in the `README.md` file.

**Comment by qbit** [comment]
Hi, you can indeed run without auth. The syntax is `widdler -auth=false` and with this enabled no user directories are created.

I hesitate to document all the options in the readme, but I will add a blurb about disabling auth, as it isn't explicitly clear what format to use :).

**Comment by qbit** [comment]
Added some examples in the latest push! Gonna close this now - thanks for reporting!
