### ISSUE TITLE
Feature request: Could you add header Authentication?

### ISSUE THREAD

**Issue by mindfuucker** [qbit/widdler#4]
I'm planning to run widdler upstream of [Authentik](https://goauthentik.io). Authenticated users will reach widdler with a specific header set with their usernames. [Could this](https://tiddlywiki.com/static/WebServer%2520Parameter%253A%2520authenticated-user-header.html) be implemented in widdler?

As a sidenote: are unknown users barred or set to read-only?

**Comment by qbit** [comment]
Should be added by #5. Thanks @TheYsconator !
