### ISSUE TITLE
[IDEA] Distribute Binaries

### ISSUE THREAD

**Issue by kookma** [qbit/widdler#9]
As not every user has golang on his/her computer to build the binaries, is it possible to release the binaries specially for windows 64 as there are many users on Windows.

**Comment by qbit** [comment]
I have been planning on testing goreleaser for a while - this will give me a good opportunity :D

**Comment by qbit** [comment]
Done!

**Comment by kookma** [comment]
I announced this here

https://talk.tiddlywiki.org/t/another-tiddlywiki-saver/1803

Thanks a million!

**Comment by qbit** [comment]
Oh awesome! Thanks!

**Comment by kookma** [comment]
Aaron, I added a jump start instruction, it is a wiki post so you can edit it if it is not clear
This is for nontechnical users! See https://talk.tiddlywiki.org/t/another-tiddlywiki-saver/1803/2
